/* Generated By:JavaCC: Do not edit this line. RParserConstants.java */
package tmp.generated_r;

public interface RParserConstants {

  int EOF = 0;
  int TRAILING_COMMENT = 6;
  int SINGLE_LINE_COMMENT = 7;
  int LPAREN = 8;
  int RPAREN = 9;
  int LBRACE = 10;
  int RBRACE = 11;
  int LBRACKET = 12;
  int RBRACKET = 13;
  int SEMICOLON = 14;
  int COMMA = 15;
  int DOT = 16;
  int COLON = 17;
  int NEWLINE = 18;
  int PLUS = 19;
  int MINUS = 20;
  int MULTIPLY = 21;
  int DIVIDE = 22;
  int FLOORDIVIDE = 23;
  int POWER = 24;
  int LSHIFT = 25;
  int RSHIFT = 26;
  int MODULO = 27;
  int NOT = 28;
  int XOR = 29;
  int OR = 30;
  int AND = 31;
  int EQUAL = 32;
  int GREATER = 33;
  int LESS = 34;
  int EQEQUAL = 35;
  int EQLESS = 36;
  int EQGREATER = 37;
  int LESSGREATER = 38;
  int NOTEQUAL = 39;
  int PLUSEQ = 40;
  int MINUSEQ = 41;
  int MULTIPLYEQ = 42;
  int DIVIDEEQ = 43;
  int FLOORDIVIDEEQ = 44;
  int MODULOEQ = 45;
  int ANDEQ = 46;
  int OREQ = 47;
  int XOREQ = 48;
  int LSHIFTEQ = 49;
  int RSHIFTEQ = 50;
  int POWEREQ = 51;
  int DOLAR = 52;
  int LESSMINUS = 53;
  int AT = 54;
  int OR_BOOL = 55;
  int AND_BOOL = 56;
  int NOT_BOOL = 57;
  int IS = 58;
  int IN = 59;
  int LAMBDA = 60;
  int IF = 61;
  int ELSE = 62;
  int ELIF = 63;
  int WHILE = 64;
  int FOR = 65;
  int TRY = 66;
  int EXCEPT = 67;
  int DEF = 68;
  int CLASS = 69;
  int FINALLY = 70;
  int PRINT = 71;
  int PASS = 72;
  int BREAK = 73;
  int CONTINUE = 74;
  int RETURN = 75;
  int YIELD = 76;
  int LIBRARY = 77;
  int FROM = 78;
  int DEL = 79;
  int RAISE = 80;
  int GLOBAL = 81;
  int EXEC = 82;
  int ASSERT = 83;
  int AS = 84;
  int WITH = 85;
  int FUNCTION = 86;
  int NAME = 87;
  int LETTER = 88;
  int DECNUMBER = 89;
  int HEXNUMBER = 90;
  int OCTNUMBER = 91;
  int FLOAT = 92;
  int COMPLEX = 93;
  int EXPONENT = 94;
  int DIGIT = 95;
  int SINGLE_STRING = 104;
  int SINGLE_STRING2 = 105;
  int TRIPLE_STRING = 106;
  int TRIPLE_STRING2 = 107;
  int SINGLE_USTRING = 108;
  int SINGLE_USTRING2 = 109;
  int TRIPLE_USTRING = 110;
  int TRIPLE_USTRING2 = 111;

  int DEFAULT = 0;
  int INDENTING = 1;
  int INDENTATION_UNCHANGED = 2;
  int IN_STRING11 = 3;
  int IN_STRING21 = 4;
  int IN_STRING13 = 5;
  int IN_STRING23 = 6;
  int IN_USTRING11 = 7;
  int IN_USTRING21 = 8;
  int IN_USTRING13 = 9;
  int IN_USTRING23 = 10;
  int IN_STRING1NLC = 11;
  int IN_STRING2NLC = 12;
  int IN_USTRING1NLC = 13;
  int IN_USTRING2NLC = 14;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<TRAILING_COMMENT>",
    "<SINGLE_LINE_COMMENT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "<NEWLINE>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"//\"",
    "\"**\"",
    "\"<<\"",
    "\">>\"",
    "\"%\"",
    "\"~\"",
    "\"^\"",
    "\"|\"",
    "\"&\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "\"!=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"//=\"",
    "\"%=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"**=\"",
    "\"$\"",
    "\"<-\"",
    "\"@\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"is\"",
    "\"in\"",
    "\"lambda\"",
    "\"if\"",
    "\"else\"",
    "\"elif\"",
    "\"while\"",
    "\"for\"",
    "\"try\"",
    "\"except\"",
    "\"def\"",
    "\"class\"",
    "\"finally\"",
    "\"print\"",
    "\"pass\"",
    "\"break\"",
    "\"continue\"",
    "\"return\"",
    "\"yield\"",
    "\"library\"",
    "\"from\"",
    "\"del\"",
    "\"raise\"",
    "\"global\"",
    "\"exec\"",
    "\"assert\"",
    "\"as\"",
    "\"with\"",
    "\"function\"",
    "<NAME>",
    "<LETTER>",
    "<DECNUMBER>",
    "<HEXNUMBER>",
    "<OCTNUMBER>",
    "<FLOAT>",
    "<COMPLEX>",
    "<EXPONENT>",
    "<DIGIT>",
    "<token of kind 96>",
    "<token of kind 97>",
    "<token of kind 98>",
    "<token of kind 99>",
    "<token of kind 100>",
    "<token of kind 101>",
    "<token of kind 102>",
    "<token of kind 103>",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "\"\\\"\\\"\\\"\"",
    "\"\\\\\\r\\n\"",
    "<token of kind 113>",
    "\"\\\\\\r\\n\"",
    "<token of kind 115>",
    "\"\\\\\\r\\n\"",
    "<token of kind 117>",
    "\"\\\\\\r\\n\"",
    "<token of kind 119>",
    "\"\"",
    "\"\"",
    "\"\"",
    "\"\"",
    "<token of kind 124>",
    "<token of kind 125>",
    "\"\\r\\n\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 129>",
    "<token of kind 130>",
    "\"`\"",
  };

}
